CREATE DATABASE GlowGuru ;
USE GlowGuru;

CREATE TABLE admin (
id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(50) NOT NULL,
name VARCHAR(50) NOT NULL,
image VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);
-- product table
CREATE TABLE product (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
image VARCHAR(50) NOT NULL,
price VARCHAR(50) NOT NULL,
quantity VARCHAR(50) NOT NULL,
description VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);